"""
Sovereign Aegis Verifier for KRYVARACODE.
Ensures that any code generated by the Forge or executed by the Eye
is scanned for safety invariant violations before execution.
"""

import logging
from typing import Any

from src.agent.aegis.invariants import RiskLevel, SafetyInvariant, check_violation

logger = logging.getLogger(__name__)


class AegisVerifier:
    """
    The Verifier acts as the final gatekeeper.
    It integrates with the ToolForge's synthesis loop to reject dangerous tools.
    """

    def verify_code(
        self, code: str, metadata: dict[str, Any]
    ) -> tuple[bool, list[SafetyInvariant] | None, int]:
        """
        Scans the provided code against the Aegis safety registry.

        Args:
            code: The source code to be verified.
            metadata: Metadata about the tool (e.g., intended goal, author role, target_path).

        Returns:
            (is_safe, violations, total_risk_score): Boolean verdict, list of violations, and aggregate risk score.
        """
        target_path = metadata.get("target_path")
        logger.info(
            f"Aegis Verifier scanning code for tool: {metadata.get('tool_name', 'unknown')} "
            f"Target: {target_path}"
        )

        violations = check_violation(code, target_path=target_path)

        if not violations:
            logger.info("Code passed safety scan. Verdict: SAFE.")
            return True, None, 0

        total_risk_score = sum(v.risk_level.value for v in violations)

        critical_violations = [
            v for v in violations if v.risk_level == RiskLevel.CRITICAL
        ]

        if critical_violations:
            logger.error(
                f"CRITICAL safety violation detected! {len(critical_violations)} critical rules broken."
            )
            return False, violations, total_risk_score

        if total_risk_score >= 3:
            logger.warning(
                f"Aggregate risk score {total_risk_score} exceeds threshold (3). Rejecting."
            )
            return False, violations, total_risk_score

        logger.warning(
            f"Safety violations detected: {len(violations)} rules broken. Score: {total_risk_score}."
        )
        return False, violations, total_risk_score

    def scan_tool_definition(self, tool_def: dict[str, Any]) -> bool:
        """
        Higher-level utility to verify a full tool definition.
        """
        code = tool_def.get("code", "")
        metadata = {
            "tool_name": tool_def.get("name", "unknown"),
            "target_path": tool_def.get("target_path"),
        }

        is_safe, _, _ = self.verify_code(code, metadata)
        return is_safe


# Global singleton
aegis_verifier = AegisVerifier()
