"""add audit log and scheduled jobs

Revision ID: 96af740d1ab7
Revises: bee0e33979a7
Create Date: 2026-09-08 15:37:47.426725+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96af740d1ab7"
down_revision: Union[str, None] = "bee0e33979a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("arguments", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_log_tool_name"), ["tool_name"], unique=False
        )

    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scheduled_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scheduled_jobs_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_scheduled_jobs_name"), ["name"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_scheduled_jobs_tool_name"), ["tool_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scheduled_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduled_jobs_tool_name"))
        batch_op.drop_index(batch_op.f("ix_scheduled_jobs_name"))
        batch_op.drop_index(batch_op.f("ix_scheduled_jobs_id"))

    op.drop_table("scheduled_jobs")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_tool_name"))
        batch_op.drop_index(batch_op.f("ix_audit_log_id"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
