"""
SandboxExecutor for KRYVARACODE Omega-Prime.
Executes synthesized code in an isolated process to prevent system corruption.

Security Model:
---------------
This sandbox provides subprocess-level isolation only. It does NOT use Docker/Podman
containers, so it provides defense-in-depth rather than hard isolation.

What it protects against:
- Accidental infinite loops (via timeout)
- Accidental memory exhaustion (via subprocess memory limits)
- Accidental file system access outside temp directory (limited by OS permissions)
- Basic code injection via argument passing (fixed via json.dumps + ast.literal_eval)

Known Limitations (subprocess-only, no container isolation):
- Malicious code can still access the file system within OS permissions
- Malicious code can still make network connections
- Malicious code can still spawn child processes
- Malicious code can still access environment variables
- No CPU/memory cgroups enforcement (reliant on OS ulimits)
- No seccomp/syscall filtering
- No namespace isolation (PID, network, mount, user)

Recommendations for production:
- Add Docker/Podman container isolation with --read-only, --cap-drop=ALL
- Use gVisor or Kata Containers for stronger kernel isolation
- Implement seccomp profiles to restrict syscalls
- Add network namespace isolation
- Use dedicated non-root user with minimal permissions
- Mount only required volumes read-only

THREAT MODEL: This sandbox assumes the SYNTHESIZED CODE is untrusted (generated by LLM).
The ARGS passed to the sandbox are also considered untrusted (user-controlled).
The WRAPPER CODE generated by _wrap_code is TRUSTED (generated by this module).
"""

import ast
import json
import logging
import os
import subprocess
import sys
import tempfile
from typing import Any

logger = logging.getLogger(__name__)


class SandboxError(Exception):
    """Custom exception for sandbox execution failures."""


# Allowlist of safe builtins for the sandboxed environment.
# These are the only builtins exposed to executed code.
SAFE_BUILTINS: set[str] = {
    # Constants
    "True",
    "False",
    "None",
    # Basic types
    "bool",
    "int",
    "float",
    "str",
    "list",
    "dict",
    "tuple",
    "set",
    "frozenset",
    "bytes",
    "bytearray",
    "memoryview",
    "complex",
    "range",
    "slice",
    "Ellipsis",
    "NotImplemented",
    # Exceptions
    "BaseException",
    "Exception",
    "ArithmeticError",
    "AssertionError",
    "AttributeError",
    "BufferError",
    "EOFError",
    "ImportError",
    "IndexError",
    "KeyError",
    "KeyboardInterrupt",
    "LookupError",
    "MemoryError",
    "NameError",
    "OSError",
    "OverflowError",
    "RecursionError",
    "ReferenceError",
    "RuntimeError",
    "StopIteration",
    "StopAsyncIteration",
    "SyntaxError",
    "SystemError",
    "SystemExit",
    "TypeError",
    "ValueError",
    "ZeroDivisionError",
    # Functions - safe subset
    "len",
    "min",
    "max",
    "sum",
    "abs",
    "round",
    "pow",
    "divmod",
    "sorted",
    "reversed",
    "enumerate",
    "zip",
    "map",
    "filter",
    "any",
    "all",
    "iter",
    "next",
    "chr",
    "ord",
    "hex",
    "oct",
    "bin",
    "format",
    "repr",
    "ascii",
    "hash",
    "id",
    "isinstance",
    "issubclass",
    "callable",
    "hasattr",
    "getattr",
    "setattr",
    "delattr",
    "vars",
    "dir",
    "type",
    "object",
    "super",
    "property",
    "classmethod",
    "staticmethod",
    # I/O - limited
    "print",
    "open",
    "input",
    # Math/utility
    # Debugging - limited
    "breakpoint",
}

# Forbidden patterns that indicate potential code injection or escape attempts.
# These are checked in the synthesized code (not the wrapper).
FORBIDDEN_PATTERNS: set[str] = {
    "__import__",
    "exec",
    "eval",
    "compile",
    "getattr",
    "setattr",
    "delattr",
    "globals",
    "locals",
    "dir",
    "vars",
    "__builtins__",
    "__globals__",
    "__locals__",
    "__class__",
    "__subclasses__",
    "__mro__",
    "__bases__",
    "importlib",
    "importlib.import_module",
    "sys.modules",
    "os.system",
    "os.popen",
    "subprocess.Popen",
    "subprocess.run",
    "subprocess.call",
    "subprocess.check_output",
    "ctypes",
    "ctypes.CDLL",
    "ctypes.windll",
    "resource",
    "resource.setrlimit",
    "signal",
    "signal.signal",
    "threading",
    "multiprocessing",
    "socket",
    "urllib",
    "requests",
    "http.client",
    "ftplib",
    "telnetlib",
    "smtplib",
    "poplib",
    "imaplib",
    "nntplib",
    "xmlrpc",
    "pickle.loads",
    "pickle.load",
    "marshal.loads",
    "marshal.load",
    "shelve.open",
    "dbm.open",
    "sqlite3.connect",
    "ctypes.cast",
    "ctypes.addressof",
    "ctypes.string_at",
    "gc.get_objects",
    "gc.get_referrers",
    "inspect.currentframe",
    "inspect.getframeinfo",
    "inspect.getouterframes",
    "sys._getframe",
    "sys._current_frames",
    "sys.settrace",
    "sys.setprofile",
    "sys.setrecursionlimit",
    "sys.setcheckinterval",
    "sys.setdlopenflags",
    "sys.set_int_max_str_digits",
    "sys.setswitchinterval",
    "types.FunctionType",
    "types.CodeType",
    "types.FrameType",
    "types.GeneratorType",
    "types.TracebackType",
}


class SandboxExecutor:
    """
    Executes Python code in an isolated subprocess.
    Future versions will upgrade to Docker/Podman for hard isolation.
    """

    def __init__(self, timeout: int = 30):
        self.timeout = timeout

    def execute(self, code: str, args: dict[str, Any] | None = None) -> tuple[Any | None, str | None]:
        """
        Executes the provided code in a separate process.

        Args:
            code: The Python source code to execute.
            args: Arguments to pass to the synthesized function.

        Returns:
            A tuple of (result, error_message).
        """
        # Validate the code before execution
        validation_error = self._validate_code(code)
        if validation_error:
            logger.error(f"Sandbox code validation failed: {validation_error}")
            return None, f"Code validation failed: {validation_error}"

        # Create a temporary file for the code
        with tempfile.NamedTemporaryFile(suffix=".py", delete=False) as tmp:
            # We wrap the code to handle argument passing and result capturing
            wrapped_code = self._wrap_code(code, args)
            tmp.write(wrapped_code.encode("utf-8"))
            tmp_path = tmp.name

        try:
            # Run the code using the current Python interpreter
            result = subprocess.run(
                [sys.executable, tmp_path],
                capture_output=True,
                text=True,
                timeout=self.timeout,
                check=False,
            )

            if result.returncode != 0:
                logger.error(f"Sandbox execution failed: {result.stderr}")
                return None, result.stderr

            # The result is expected to be printed to stdout as a representation
            # In a real implementation, we'd use a structured format like JSON
            return self._parse_result(result.stdout.strip()), None

        except subprocess.TimeoutExpired:
            logger.error("Sandbox execution timed out.")
            return None, "Timeout expired"
        except OSError as e:
            logger.error(f"Unexpected sandbox OS error: {e}")
            return None, str(e)
        except ValueError as e:
            logger.error(f"Unexpected sandbox value error: {e}")
            return None, str(e)
        except RuntimeError as e:
            logger.error(f"Unexpected sandbox runtime error: {e}")
            return None, str(e)
        finally:
            # Cleanup temporary file
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

    def _validate_code(self, code: str) -> str | None:
        """
        Validates that the synthesized code doesn't contain forbidden patterns.
        Uses AST parsing for more accurate detection than string matching.

        Returns:
            Error message if validation fails, None if validation passes.
        """
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return f"Syntax error in synthesized code: {e}"

        # Walk the AST and check for forbidden patterns
        for node in ast.walk(tree):
            # Check for forbidden function calls
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    if node.func.id in FORBIDDEN_PATTERNS:
                        return f"Forbidden function call: {node.func.id}"
                elif isinstance(node.func, ast.Attribute):
                    # Check for attribute access like os.system, subprocess.run, etc.
                    attr_name = self._get_full_attribute_name(node.func)
                    if attr_name and any(forbidden in attr_name for forbidden in FORBIDDEN_PATTERNS):
                        return f"Forbidden attribute access: {attr_name}"

            # Check for forbidden attribute access (e.g., __class__, __subclasses__)
            if isinstance(node, ast.Attribute) and node.attr in FORBIDDEN_PATTERNS:
                return f"Forbidden attribute access: {node.attr}"

            # Check for forbidden imports
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                for alias in node.names:
                    if alias.name in FORBIDDEN_PATTERNS:
                        return f"Forbidden import: {alias.name}"
                    # Check for dangerous submodules
                    if any(forbidden in alias.name for forbidden in FORBIDDEN_PATTERNS):
                        return f"Forbidden import pattern: {alias.name}"

        return None

    def _get_full_attribute_name(self, node: ast.Attribute) -> str | None:
        """Extracts the full attribute name from an ast.Attribute node (e.g., os.system)."""
        parts = []
        current = node
        while isinstance(current, ast.Attribute):
            parts.append(current.attr)
            current = current.value
        if isinstance(current, ast.Name):
            parts.append(current.id)
            return ".".join(reversed(parts))
        return None

    def _wrap_code(self, code: str, args: dict[str, Any] | None) -> str:
        """
        Wraps the synthesized code to call the target function with provided args
        and print the result to stdout.

        SECURITY: Args are serialized to JSON, then base64-encoded before embedding
        in the generated code. This prevents code injection that f-string interpolation
        would allow — base64 output is always [A-Za-z0-9+/=], safe for any string
        context. The generated code decodes and json.loads() at runtime.
        """
        import base64 as _b64

        import_block = "import json\nimport sys\nimport base64\n"

        # Serialize args to JSON, then base64-encode for safe embedding.
        # Base64 output contains only [A-Za-z0-9+/=], immune to quote/escape issues.
        args_b64 = _b64.b64encode(json.dumps(args or {}).encode("utf-8")).decode("ascii")

        wrapper = f"""
{import_block}
{code}

if __name__ == "__main__":
    try:
        # Try to find the main execution function
        # In production, the synthesizer would provide the exact function name
        import inspect
        curr_module = sys.modules['__main__']
        funcs = [name for name, obj in inspect.getmembers(curr_module) if inspect.isfunction(obj)]

        target_func = None
        for name in ['execute', 'main', 'run']:
            if name in funcs:
                target_func = getattr(curr_module, name)
                break

        if target_func is None and funcs:
            target_func = getattr(curr_module, funcs[0])

        if target_func:
            # SECURITY: Deserialize args via base64 decode + json.loads.
            # Base64 is immune to quote/escape injection in f-strings.
            args_val = json.loads(base64.b64decode("{args_b64}").decode("utf-8"))
            result = target_func(**args_val)
            print(json.dumps(result, default=str))
        else:
            print("Error: No executable function found in synthesized code.")
            sys.exit(1)
    except Exception as e:
        print(f"Runtime Error: {{e}}")
        sys.exit(1)
"""
        return wrapper

    def _parse_result(self, stdout: str) -> Any:
        """
        Parses the result from stdout.
        Expects JSON output from the wrapper.
        """
        try:
            return json.loads(stdout)
        except json.JSONDecodeError:
            # Fallback: return raw string if not JSON
            return stdout


# Global singleton
executor = SandboxExecutor()
